remote_theme: "mmistakes/minimal-mistakes@4.17.2"
plugins:
  - jekyll-relative-links
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
relative_links:
  enabled: true
  collections: true
include:
  - CONTRIBUTING.md
  - README.md
  - LICENSE.md
  - COPYING.md
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - ISSUE_TEMPLATE.md
  - PULL_REQUEST_TEMPLATE.md
